export const GET_USER_LIST_REQUESTING = 'GET_USER_LIST_REQUESTING';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILED = 'GET_USER_LIST_FAILED';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
